package com.geek45.mybatisdemo.dal.model;

import javax.annotation.Generated;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table geek_app
 */
public class GeekApp implements Serializable {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.id")
    private Integer id;

    /**
     * Database Column Remarks:
     *   应用名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_name")
    private String appName;

    /**
     * Database Column Remarks:
     *   app秘钥
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_key")
    private String appKey;

    /**
     * Database Column Remarks:
     *   appId
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_id")
    private String appId;

    /**
     * Database Column Remarks:
     *   应用说明
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.note")
    private String note;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.create_time")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   最后修改时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.modify_time")
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   状态
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.status")
    private String status;

    /**
     * Database Column Remarks:
     *   删除标识
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.deleted")
    private Integer deleted;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: geek_app")
    private static final long serialVersionUID = 1L;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.id")
    public Integer getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.id")
    public void setId(Integer id) {
        this.id = id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_name")
    public String getAppName() {
        return appName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_name")
    public void setAppName(String appName) {
        this.appName = appName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_key")
    public String getAppKey() {
        return appKey;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_key")
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_id")
    public String getAppId() {
        return appId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.app_id")
    public void setAppId(String appId) {
        this.appId = appId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.note")
    public String getNote() {
        return note;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.note")
    public void setNote(String note) {
        this.note = note;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.create_time")
    public Date getCreateTime() {
        return createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.create_time")
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.modify_time")
    public Date getModifyTime() {
        return modifyTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.modify_time")
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.status")
    public String getStatus() {
        return status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.status")
    public void setStatus(String status) {
        this.status = status;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.deleted")
    public Integer getDeleted() {
        return deleted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: geek_app.deleted")
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: geek_app")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appName=").append(appName);
        sb.append(", appKey=").append(appKey);
        sb.append(", appId=").append(appId);
        sb.append(", note=").append(note);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", status=").append(status);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}